# Generated by Django 4.1.5 on 2023-01-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0003_rename_comment_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
